### ISSUE TITLE
Release 0.18

### ISSUE THREAD

**Issue by knight-of-ni** [toddr/Sys-Mmap#7]
Hi,
I was alerted to the new 0.18 release on cpan, but it appears the Changes doc was not updated to include what has changed. Additionally, the github site still shows 0.17_1 as the latest release. Naturally, this isn't a big deal. However, before I push 0.18 package to the Fedora repos, it would be nice if there was some kind of text included which summarizes what has changed or fixed in this release. I can patch in whatever changes you might make in github, so there is no need to push a new release on cpan if you don't want to. Thank you.

**Comment by scottwalters** [comment]
Oops, yeah, it looks like I had a spaz attack before committing/pushing.  Thank you for nudging me.  Changes updated and everything pushed back.

**Comment by scottwalters** [comment]
... Changes changes didn't make it into the CPAN release but the github version at least has them.  If this jams the works, holler, and I'll rev to 0.19.

**Comment by knight-of-ni** [comment]
Thanks for updating the Changes file @scrottie and keeping this project alive. My own project relies on this perl module.

Note sure if you noticed, but the project releases pages still shows 0.17_01 as the latest:
https://github.com/toddr/Sys-Mmap/releases

Again, not a big deal, but it might cause confusion with the casual user if it doesn't match what is on cpan. Maybe you know this already, but you can add a new 0.18 release right from that page via the browser or create an annotative tag from the commandline then push it to master.
